mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("create/", views.tweet_create_view, name="create"),
    path("<int:pk>/", views.tweet_detail_view, name="detail"),
    path("<int:pk>/delete/", views.tweet_delete_view, name="delete"),
    path("<int:pk>/like/", views.like_view, name="like"),
    path("<int:pk>/unlike/", views.unlike_view, name="unlike"),
]

tweets/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class Like(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["tweet", "user"], name="like_unique")
        ]

tweets/forms.py
from django import forms

from .models import Tweet


class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = {"content"}
        widgets = {
            "content": forms.Textarea(attrs={"placeholder": "今どうしてる？"}),
        }
        labels = {"content": ""}

tweets/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .forms import TweetForm
from .models import Like, Tweet


def tweet_create_view(request):
    if request.method == "POST":
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.user = request.user
            tweet.save()
            return redirect("welcome:index")
    else:
        form = TweetForm()
    context = {"form": form}
    return render(request, "tweets/create.html", context)


def tweet_detail_view(request, pk):
    tweet = Tweet.objects.get(pk=pk)
    liked_list = Like.objects.filter(user=request.user).values_list("tweet", flat=True)
    the_number_of_likes = tweet.like_set.count()
    context = {
        "tweet": tweet,
        "liked_list": liked_list,
        "the_number_of_likes": the_number_of_likes,
    }
    return render(request, "tweets/detail.html", context)


def tweet_delete_view(request, pk):
    template_name = "tweets/delete.html"
    tweet = get_object_or_404(Tweet, pk=pk)
    context = {"tweet": tweet}
    if tweet.user == request.user:
        if request.method == "POST":
            tweet.delete()
            return redirect("welcome:index")
        return render(request, template_name, context)
    else:
        raise PermissionDenied


@login_required
def like_view(request, pk, *args, **kwargs):
    tweet = get_object_or_404(Tweet, pk=pk)
    Like.objects.get_or_create(user=request.user, tweet=tweet)
    context = {
        "the_number_of_likes": tweet.like_set.count(),
        "tweet.pk": tweet.pk,
    }
    return JsonResponse(context)


@login_required
def unlike_view(request, pk, *args, **kwargs):

    tweet = get_object_or_404(Tweet, pk=pk)
    like = Like.objects.filter(user=request.user, tweet=tweet)

    if like.exists():
        like.delete()
        context = {
            "the_number_of_likes": tweet.like_set.count(),
            "tweet.pk": tweet.pk,
        }
        return JsonResponse(context)
    else:
        raise Http404

tweets/templates/tweets/create.html
{% extends 'accounts/base.html' %}

{% block content %}
<form action="{% url 'tweets:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">呟く</button>
</form>
{% endblock %}

tweets/templates/tweets/delete.html
{% extends 'accounts/base.html' %}

{% block content %}
<p>{{ tweet.user }}のツイート</p>
<p>{{ tweet.content | linebreaksbr }}</p>
<p>{{ tweet.created_at }}</p>
<form method="post">{% csrf_token %}
    <a class="right-field">消去すると復元できません。よろしいですか？&nbsp;&nbsp;&nbsp;</a>
    <button type="submit" name = "confirm" class="right-field">消去</button>
    <a href="{% url 'tweets:detail' tweet.pk %}" class="right-field">キャンセル</a>
</form>
{% endblock %}

tweets/templates/tweets/detail.html
{% extends 'accounts/base.html' %}

{% block content %}
<p>{{ tweet.user }}のツイート</p>
<p>{{ tweet.content | linebreaksbr }}</p>
<p>{{ tweet.created_at }}</p>
<p>{% include 'tweets/like.html' %}</P>
<span id="like-for-tweet-count">{{ the_number_of_likes }}</span>
<span>件のイイね</span>
{% if tweet.user == request.user %}
<a type="button" data-mdb-ripple-color="dark" href="{% url 'tweets:delete' tweet.pk %}">削除</a>
{% endif %}
{% block extrajs %}
{% include 'accounts/script.html' %}
{% endblock extrajs %}
{% endblock content %}

tweets/templates/tweets/like.html
{% if tweet.pk in liked_list %}
<button type="button" id="ajax-like-for-tweet" style="border:none;background:none;color:red" data-is-liked="true"
    class="like_button" pk="{{tweet.pk}}">
    <!-- すでにイイねしている時はfasクラス -->
    <i class="fas fa-heart text-danger" id="like-for-tweet-icon{{tweet.pk}}"></i>
</button>
{% else %}
<button type="button" id="ajax-like-for-tweet" style="border:none;background:none;color:red" data-is-liked="false"
    class="like_button" pk="{{tweet.pk}}">
    <!-- イイねしていないときはfarクラス -->
    <i class="far fa-heart text-danger" id="like-for-tweet-icon{{tweet.pk}}"></i>
</button>
{% endif %}

tweets/templates/tweets/like_component.html
{% if tweet.pk in liked_list %}
<button type="button" id="ajax-like-for-tweet" style="border:none;background:none;color:red" data-is-liked="true"
    class="like_button" pk="{{tweet.pk}}">
    <!-- すでにイイねしている時はfasクラス -->
    <i class="fas fa-heart text-danger" id="like-for-tweet-icon{{tweet.pk}}"></i>
</button>
{% else %}
<button type="button" id="ajax-like-for-tweet" style="border:none;background:none;color:red" data-is-liked="false"
    class="like_button" pk="{{tweet.pk}}">
    <!-- イイねしていないときはfarクラス -->
    <i class="far fa-heart text-danger" id="like-for-tweet-icon{{tweet.pk}}"></i>
</button>
{% endif %}

tweets/templates/tweets/tweet_create.html
{% extends 'accounts/base.html' %}

{% block content %}
<form action="{% url 'tweets:tweet_create' %}" method="post">
    {% csrf_token %}
    {{ tweet.as_p }}
    <button type="submit">呟く</button>
</form>
{% endblock %}

tweets/templates/tweets/tweet_delete.html
{% extends 'accounts/base.html' %}

{% block content %}
<p>{{ tweet.user }}</p>
<p>{{ tweet.content | linebreaksbr }}</p>
<p>{{ tweet.created_at }}</p>
<form method="post">{% csrf_token %}
    <a class="right-field">消去すると復元できません。よろしいですか？&nbsp;&nbsp;&nbsp;</a>
    <button type="submit" name = "confirm" class="right-field">消去</button>
    <a href="{% url 'tweets:tweet_detail' tweet.pk %}" class="right-field">キャンセル</a>
</form>
{% endblock %}

tweets/templates/tweets/tweet_detail.html
{% extends 'accounts/base.html' %}

{% block content %}
<p>{{ tweet.user }}のツイート</p>
<p>{{ tweet.content | linebreaksbr }}</p>
<p>{{ tweet.created_at }}</p>
{% if tweet.user == request.user %}
<a type="button" data-mdb-ripple-color="dark" href="{% url 'tweets:tweet_delete' tweet.pk %}">削除</a>
{% endif %}
{% endblock %}