accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("<str:username>/follow/", views.follow_view, name="follow"),
    path("<str:username>/unfollow/", views.unfollow_view, name="unfollow"),
    path(
        "<str:username>/followee_list/",
        views.followee_list_view,
        name="followee_list",
    ),
    path(
        "<str:username>/follower_list/", views.follower_list_view, name="follower_list"
    ),
    path("<str:username>/", views.user_profile_view, name="profile"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("create/", views.tweet_create_view, name="create"),
    path("<int:pk>/", views.tweet_detail_view, name="detail"),
    path("<int:pk>/delete/", views.tweet_delete_view, name="delete"),
    path("<int:pk>/like/", views.like_view, name="like"),
    path("<int:pk>/unlike/", views.unlike_view, name="unlike"),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.index_view, name="index"),
]

welcome/models.py
from django.db import models

# Create your models here.

welcome/views.py
from django.shortcuts import render
from django.views.decorators.http import require_GET
from django.contrib.auth import get_user_model

from tweets.models import Tweet, Like

User = get_user_model()


@require_GET
def index_view(request):
    tweet_list = Tweet.objects.all().order_by("created_at")
    context = {
        "tweet_list": tweet_list,
    }
    if request.user.is_authenticated:
        followee_list = request.user.followees.all()
        follower_list = request.user.followers.all()
        liked_list = Like.objects.filter(user=request.user).values_list(
            "tweet", flat=True
        )
        context = {
            **context,
            "follower_list": follower_list,
            "followee_list": followee_list,
            "liked_list": liked_list,
        }
    return render(request, "welcome/index.html", context)

welcome/templates/welcome/index.html
{% extends 'accounts/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<h1>
    おかえりなさい、
    <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:profile' user.username %}">{{ user.username }}さん</a>
</h1>

<a href="{% url 'tweets:create' %}" class="right-field">呟く</a>
<a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:followee_list' user.username %}">あなたのフォローリスト</a>
<a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:follower_list' user.username %}">あなたのフォロワーリスト</a>
{% for tweet in tweet_list %}
<p></p>
<div class="card">
    <div class="card-body">
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:profile' tweet.user.username %}">{{ tweet.user }}</a>
        {% if not tweet.user in followee_list and not tweet.user == request.user %}
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:follow' tweet.user.username %}">フォロー</a>
        {% elif tweet.user in followee_list %}
        <p>
            フォローしています
            <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:unfollow' tweet.user.username %}">アンフォロー</a>
        </p>

        {% endif %}
        {% if tweet.user in follower_list%}
        <p>フォローされています</p>
        {% endif %}
        <div>
            <p>{{ tweet.content | linebreaksbr }}</p>
        </div>
        <div align="right">
            <a type="button" class="btn btn-outline-primary" "text-end" data-mdb-ripple-color="dark"
                href="{% url 'tweets:detail' tweet.pk %}">
                詳細
            </a>
            {% include 'tweets/like.html' %}
        </div>
    </div>
</div>
{% empty %}
<h4 class="text-center my-3">ツイートはありません。</h4>
{% endfor %}
{% else %}
<h1>Backend Final Assignment</h1>
{% endif %}
{% block extrajs %}
{% include 'accounts/script.html' %}
{% endblock extrajs %}
{% endblock content %}