accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("<str:username>/follow/", views.follow_view, name="follow"),
    path("<str:username>/unfollow/", views.unfollow_view, name="unfollow"),
    path(
        "<str:username>/followee_list/",
        views.followee_list_view,
        name="followee_list",
    ),
    path(
        "<str:username>/follower_list/", views.follower_list_view, name="follower_list"
    ),
    path("<str:username>/", views.user_profile_view, name="profile"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("create/", views.tweet_create_view, name="create"),
    path("<int:pk>/", views.tweet_detail_view, name="detail"),
    path("<int:pk>/delete/", views.tweet_delete_view, name="delete"),
    path("<int:pk>/like/", views.like_view, name="like"),
    path("<int:pk>/unlike/", views.unlike_view, name="unlike"),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.index_view, name="index"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    followees = models.ManyToManyField(
        "CustomUser",
        verbose_name="フォロー中のユーザー",
        through="FollowConnection",
        related_name="+",
        through_fields=("follower", "followee"),
    )
    followers = models.ManyToManyField(
        "CustomUser",
        verbose_name="フォローされているユーザー",
        through="FollowConnection",
        related_name="+",
        through_fields=("followee", "follower"),
    )


class FollowConnection(models.Model):
    follower = models.ForeignKey(
        "CustomUser",
        on_delete=models.CASCADE,
        related_name="followee_followconnections",
    )
    followee = models.ForeignKey(
        "CustomUser",
        on_delete=models.CASCADE,
        related_name="follower_followconnections",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["follower", "followee"], name="followconnection_unique"
            ),
        ]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(AuthenticationForm):
    pass

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth import get_user_model

from .forms import SignupForm, LoginForm
from .models import FollowConnection
from tweets.models import Tweet


User = get_user_model()


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("welcome:index")
    else:
        form = SignupForm()
    return render(request, "accounts/signup.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user.is_active:
                login(request, user)
                return redirect("welcome:index")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("welcome:index")


def follow_view(request, username):
    follow_user = get_object_or_404(User, username=username)
    if follow_user == request.user:
        return render(request, "welcome/index.html", status=404)
    else:
        FollowConnection.objects.create(follower=request.user, followee=follow_user)
        return redirect("welcome:index")


def unfollow_view(request, username):
    unfollow_user = get_object_or_404(User, username=username)
    if unfollow_user == request.user:
        return render(request, "welcome/index.html", status=404)
    delete_user = get_object_or_404(
        FollowConnection, follower=request.user, followee=unfollow_user
    )
    delete_user.delete()
    return redirect("welcome:index")


def followee_list_view(request, username):
    user = User.objects.prefetch_related("followers", "followees").get(
        username=username
    )
    followee_list = user.followees.all()
    follower_list = user.followers.all()
    context = {
        "username": username,
        "followee_list": followee_list,
        "follower_list": follower_list,
    }
    return render(request, "accounts/followee_list.html", context)


def follower_list_view(request, username):
    user = User.objects.prefetch_related("followers", "followees").get(
        username=username
    )
    followee_list = user.followees.all()
    follower_list = user.followers.all()
    context = {
        "username": username,
        "followee_list": followee_list,
        "follower_list": follower_list,
    }
    return render(request, "accounts/follower_list.html", context)


def user_profile_view(request, username):
    user = User.objects.prefetch_related("followers", "followees").get(
        username=username
    )
    tweet_list = Tweet.objects.filter(user=user).order_by("created_at")
    followee_list = user.followees.all()
    follower_list = user.followers.all()
    context = {
        "username": username,
        "tweet_list": tweet_list,
        "followee_list": followee_list,
        "follower_list": follower_list,
    }
    return render(request, "accounts/profile.html", context)

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/5.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/5.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
</head>

<body>
    <div class="left-field">
        <a href="{% url 'welcome:index' %}" class="left-field">Twitter Clone</a>
    {% if user.is_authenticated %}
    </div>
    <div class="right-field">
        <a class="right-field">ユーザ：{{ user.username }}&nbsp;&nbsp;&nbsp;</a>
        <a href="{% url 'accounts:logout' %}" class="right-field">ログアウト</a>
    </div>
    {% else %}
    </div>
    <div class="right-field">
        <a href="{% url 'accounts:login' %}" class="right-field">ログイン</a>
        <a href="{% url 'accounts:signup' %}" class="right-field">登録</a>
    </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>

</html>

accounts/templates/accounts/followee_list.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>{{ username }}さんがフォロー中のユーザー</h1>
{% for followee in followee_list %}
<p></p>
<div class="card">
    <div class="card-body">
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:profile' followee.username %}">{{ followee.username }}</a>
        {% if followee in follower_list %}
        <p>フォローされています</p>
        {% endif %}
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:unfollow' followee.username %}">アンフォロー</a>
    </div>
</div>
{% empty %}
<h4 class="text-center my-3">{{ user.username }}は誰もフォローしていません。</h4>
{% endfor %}
{% endblock %}

accounts/templates/accounts/follower_list.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>{{ username }}さんをフォロー中のユーザー</h1>
{% for follower in follower_list %}
<div class="card">
    <div class="card-body">
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:profile' follower.username %}">{{ follower.username }}</a>
        {% if follower not in followee_list %}
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:follow' follower.username %}">フォロー</a>
        {% elif follower in followee_list %}
        <p>フォローしています</p>
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:unfollow' follower.username %}">アンフォロー</a>
        {% endif %}
    </div>
</div>
{% empty %}
<h4 class="text-center my-3">{{ user.username }}は誰からもフォローされていません。</h4>
{% endfor %}
{% endblock %}

accounts/templates/accounts/following_list.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>{{ username }}さんがフォロー中のユーザー</h1>
{% for followee in followee_list %}
<p></p>
<div class="card">
    <div class="card-body">
        <p>{{ followee.username }}</p>
        {% if followee in follower_list %}
        <p>フォローされています</p>
        {% endif %}
        <a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:unfollow' followee.username %}">アンフォロー</a>
    </div>
</div>
{% empty %}
<h4 class="text-center my-3">{{ user.username }}は誰もフォローしていません。</h4>
{% endfor %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>ログイン</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">ログイン</button>
    <p><a href="{% url 'accounts:signup'%}">登録</a></p>
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>{{ username }}さん</h1>
<a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:followee_list' username %}">フォロー数：{{ followee_list | length}}</a>
<a type="button" data-mdb-ripple-color="dark" href="{% url 'accounts:follower_list' username %}">フォロワー数：{{ follower_list | length}}</a>
{% for tweet in tweet_list %}
<p>{{ username }}のツイート</p>
<div class="card">
    <div class="card-body">
        <div>
            <p>{{ tweet.content | linebreaksbr }}</p>
        </div>
        <div align="right">
            <a type="button" class="btn btn-outline-primary" "text-end" data-mdb-ripple-color="dark"
                href="{% url 'tweets:detail' tweet.pk %}">
                詳細
            </a>
            {% include 'tweets/like.html' %}
        </div>
    </div>
</div>
{% empty %}
<h4 class="text-center my-3">{{ username }}はまだ何も呟いていません。</h4>
{% endfor %}
{% block extrajs %}
{% include 'accounts/script.html' %}
{% endblock extrajs %}
{% endblock content %}

accounts/templates/accounts/script.html
<script type="text/javascript">
    const getCookie = name => {
        if (document.cookie && document.cookie !== '') {
            for (const cookie of document.cookie.split(';')) {
                const [key, value] = cookie.trim().split('=');
                if (key === name) {
                    return decodeURIComponent(value);
                }
            }
        }
    };

    const csrftoken = getCookie('csrftoken');
    // console.log(LikeButtons)


    window.addEventListener('DOMContentLoaded', function () {
        const element = document.getElementsByClassName('like_button'); // ①

        for (let i = 0; i < element.length; i++) { // ②
            element[i].addEventListener('click', function () { // ②
                pk = Number(element[i].getAttribute('pk'));

                if ((element[i].dataset.isLiked) == 'true') {

                    url = "{% url 'tweets:unlike' 123456 %}".replace(/123456/, pk);
                }
                else {
                    url = "{% url 'tweets:like' 123456 %}".replace(/123456/, pk);
                }
                fetch(url, {
                    method: 'POST',
                    body: `tweet.pk={{tweet.pk}}`,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                }).then(response => {
                    return response.json();
                }).then(response => {
                    const icon = document.getElementById('like-for-tweet-icon' + pk)

                    if (element[i].dataset.isLiked == 'false') {
                        element[i].dataset.isLiked = 'true'
                        icon.classList.remove('far')
                        icon.classList.add('fas')

                    } else {
                        element[i].dataset.isLiked = 'false'
                        icon.classList.remove('fas')
                        icon.classList.add('far')

                    }
                })
                    .catch(error => {
                        console.log(error);
                    });
            })

        }
    })


</script>

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>ユーザー登録</h1>
<form action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">登録</button>
</form>
{% endblock %}